#define GRAVITY 10.0f
#define FPS 30
#define PLAYER_SPRITE_COLS 4
#define PLAYER_TILE_SIZE 50
#define BAT_SPRITE_COLS 2
#define BAT_TILE_SIZE 32
#define FOX_SPRITE_COLS 2
#define FOX_TILE_SIZE 32
#define GROUND_SPRITE_COLS 4
#define GROUND_TILE_SIZE 32

