#define GRAVITY 9.81f;
#define FPS 30
#define PLAYER_SPRITE_COLS 4
#define PLAYER_TILE_SIZE 50
#define PLAYER_SPRITESHEET_OFFSET 0
#define BAT_SPRITE_COLS 2
#define BAT_TILE_SIZE 32
#define BAT_SPRITESHEET_OFFSET 0